# Generated by Django 6.0.3 on 2026-04-11 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cajero', 'Cajero'), ('gerente', 'Gerente'), ('tesorero', 'Tesorero')], default='cajero', max_length=20),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('categoria', models.CharField(choices=[('aporte_mensual', 'Aporte Mensual Socio'), ('inscripcion', 'Inscripción de Libreta'), ('interes_credito', 'Interés de Crédito'), ('comision_banco', 'Beneficio Comisión Bancaria'), ('multa', 'Multa'), ('rifa', 'Rifa / Lotería'), ('otro_ingreso', 'Otro Ingreso'), ('desembolso_credito', 'Desembolso de Crédito'), ('devolucion_ahorro', 'Devolución de Ahorro'), ('premio_rifa', 'Premio Rifa'), ('cumpleanos', 'Regalo Cumpleaños'), ('gasto_operativo', 'Gasto Operativo'), ('otro_egreso', 'Otro Egreso')], max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('origen', models.CharField(choices=[('automatico', 'Automático (sistema)'), ('manual', 'Registro Manual')], default='manual', max_length=15)),
                ('comprobante', models.CharField(blank=True, max_length=200)),
                ('socio_ref', models.CharField(blank=True, help_text='Nombre del socio relacionado', max_length=200)),
                ('libreta_ref', models.CharField(blank=True, max_length=50)),
                ('credito_ref', models.CharField(blank=True, max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos (Ingresos/Egresos)',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
