# Generated by Django 6.0.3 on 2026-04-16 02:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfilusuario_rol_movimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='comprobante_archivo',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/movimientos/'),
        ),
        migrations.CreateModel(
            name='AuditoriaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('tesoreria', 'Tesorería'), ('verificaciones', 'Verificaciones'), ('caja', 'Caja Diaria'), ('socios', 'Socios'), ('creditos', 'Créditos'), ('multas', 'Multas'), ('seguridad', 'Seguridad'), ('reportes', 'Reportes')], max_length=20)),
                ('accion', models.CharField(max_length=80)),
                ('entidad', models.CharField(blank=True, max_length=80)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría del Sistema',
                'verbose_name_plural': 'Auditoría del Sistema',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones_apertura', models.TextField(blank=True)),
                ('observaciones_cierre', models.TextField(blank=True)),
                ('abierta_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_abiertas', to=settings.AUTH_USER_MODEL)),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja Diaria',
                'verbose_name_plural': 'Cajas Diarias',
                'ordering': ['-fecha'],
            },
        ),
    ]
