# Generated by Django 6.0.3 on 2026-04-22 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movimiento_comprobante_archivo_auditoriasistema_and_more'),
        ('socios', '0004_alter_socio_ciudad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(unique=True)),
                ('subscription_data', models.JSONField(default=dict)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('activa', models.BooleanField(default=True)),
                ('ultima_notificacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='socios.socio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción Push',
                'verbose_name_plural': 'Suscripciones Push',
                'ordering': ['-updated_at'],
            },
        ),
    ]
