# Generated by Django 6.0.3 on 2026-05-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_mantenimiento', models.BooleanField(default=False, help_text='Activa el modo mantenimiento para mostrar página de espera a los usuarios.')),
                ('mensaje_mantenimiento', models.CharField(blank=True, default='Estamos realizando mejoras en el sistema. Volvemos pronto.', help_text='Mensaje personalizado para la página de mantenimiento.', max_length=300)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
