# Generated by Django 6.0.3 on 2026-04-08 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(default='Quito', max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('es_menor', models.BooleanField(default=False)),
                ('representante_nombre', models.CharField(blank=True, max_length=200)),
                ('representante_cedula', models.CharField(blank=True, max_length=13)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('recomendado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendados', to='socios.socio')),
            ],
            options={
                'verbose_name_plural': 'Socios',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Libreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('suspendida', 'Suspendida')], default='activa', max_length=20)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('inscripcion_pagada', models.BooleanField(default=False)),
                ('fecha_inscripcion_pago', models.DateField(blank=True, null=True)),
                ('saldo_ahorro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libretas', to='socios.periodo')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libretas', to='socios.socio')),
            ],
            options={
                'verbose_name_plural': 'Libretas',
                'ordering': ['numero'],
                'unique_together': {('numero', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='AccesoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=128)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceso', to='socios.socio')),
            ],
        ),
        migrations.CreateModel(
            name='AporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.IntegerField()),
                ('monto_ahorro', models.DecimalField(decimal_places=2, default=22, max_digits=8)),
                ('monto_loteria', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('monto_cumpleanos', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('monto_total', models.DecimalField(decimal_places=2, default=24, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('reportado', 'Reportado por socio'), ('verificado', 'Verificado'), ('atrasado', 'Atrasado')], default='pendiente', max_length=20)),
                ('fecha_reporte', models.DateTimeField(blank=True, null=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('comprobante_referencia', models.CharField(blank=True, max_length=200)),
                ('observacion', models.CharField(blank=True, max_length=300)),
                ('libreta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='socios.libreta')),
            ],
            options={
                'ordering': ['anio', 'mes'],
                'unique_together': {('libreta', 'mes', 'anio')},
            },
        ),
    ]
