# Generated by Django 6.0.3 on 2026-04-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aportemensual',
            name='comprobante_archivo',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/aportes/'),
        ),
        migrations.AlterField(
            model_name='aportemensual',
            name='monto_ahorro',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8),
        ),
        migrations.AlterField(
            model_name='aportemensual',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=8),
        ),
    ]
