# Generated by Django 6.0.3 on 2026-04-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_socio_perfil_portal_bancario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='ciudad',
            field=models.CharField(default='', max_length=50),
        ),
    ]
