# Generated by Django 6.0.3 on 2026-05-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_alter_socio_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='libreta',
            name='proposito_ahorro',
            field=models.CharField(blank=True, help_text='Propósito o meta para los ahorros a fin de año', max_length=150),
        ),
    ]
