# Generated by Django 6.0.3 on 2026-04-08 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RifaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('numeros_loteria', models.CharField(blank=True, help_text='Últimos 3 números ganadores', max_length=50)),
                ('monto_premio', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('ganada', 'Ganada - Pagada'), ('no_ganada', 'No Ganada')], default='pendiente', max_length=20)),
                ('socio_al_dia', models.BooleanField(default=True, help_text='El ganador estaba al día')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('libreta_ganadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas_ganadas', to='socios.libreta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rifas', to='socios.periodo')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
    ]
