# Generated by Django 6.0.3 on 2026-04-08 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('aplica_a', models.CharField(choices=[('socio', 'Por Socio'), ('libreta', 'Por Libreta')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Multa',
                'verbose_name_plural': 'Tipos de Multa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='socios.periodo')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('reunion_asistencia', 'Reunión - Asistencia'), ('reunion_comportamiento', 'Reunión - Comportamiento'), ('mensualidad_atraso', 'Mensualidad Atrasada ($5/libreta)'), ('mensualidad_incumplimiento', 'Incumplimiento Total ($20)'), ('credito_atraso_primera', 'Crédito Atrasado 1ra vez ($10)'), ('credito_atraso_reincidente', 'Crédito Atrasado Reincidente ($30)'), ('manual', 'Aplicada Manualmente')], max_length=40)),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('condonada', 'Condonada')], default='pendiente', max_length=20)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('comprobante_pago', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('aplicada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('libreta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas', to='socios.libreta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='socios.periodo')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='socios.socio')),
                ('reunion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multas.reunion')),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ComportamientoReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('multa_generada', models.BooleanField(default=False)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comportamientos', to='socios.socio')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comportamientos', to='multas.reunion')),
                ('tipo_multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multas.tipomulta')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('atrasado_11', 'Atrasado 11-20 min - $1'), ('atrasado_21', 'Atrasado 21+ min - $3'), ('falta_justificada', 'Falta Justificada - $1/libreta'), ('falta_injustificada', 'Falta Injustificada - $3/libreta')], default='presente', max_length=25)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=300)),
                ('multas_generadas', models.BooleanField(default=False)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='socios.socio')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='multas.reunion')),
            ],
            options={
                'unique_together': {('reunion', 'socio')},
            },
        ),
    ]
