# Generated by Django 6.0.3 on 2026-04-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='comprobante_archivo',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/multas/'),
        ),
    ]
