# Generated by Django 6.0.3 on 2026-05-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0002_multa_comprobante_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='anio_origen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='mes_origen',
            field=models.IntegerField(blank=True, help_text='Mes que originó la multa', null=True),
        ),
    ]
