# Generated by Django 6.0.3 on 2026-05-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0003_multa_anio_origen_multa_mes_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='link_reunion',
            field=models.URLField(blank=True),
        ),
    ]
