# Generated by Django 6.0.3 on 2026-04-08 20:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('mensualizado', 'Mensualizado'), ('no_mensualizado', 'No Mensualizado')], max_length=20)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo_meses', models.IntegerField()),
                ('banco', models.CharField(choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('pacifico', 'Banco del Pacífico'), ('bolivariano', 'Banco Bolivariano'), ('produbanco', 'Produbanco'), ('internacional', 'Banco Internacional'), ('otro', 'Otro Banco')], max_length=30)),
                ('numero_cuenta_bancaria', models.CharField(max_length=50)),
                ('titular_cuenta', models.CharField(max_length=200)),
                ('cedula_titular', models.CharField(max_length=13)),
                ('tasa_mensual', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5)),
                ('interes_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comision_bancaria', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('beneficio_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('monto_transferir', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_pago_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('desembolsado', 'Desembolsado'), ('pagado', 'Pagado'), ('mora_leve', 'Mora Leve (≤30d)'), ('mora_media', 'Mora Media (31-60d)'), ('mora_grave', 'Mora Grave (>60d)'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_desembolso', models.DateField(blank=True, null=True)),
                ('fecha_pago_limite', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=300)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('libreta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='socios.libreta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='socios.periodo')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='socios.socio')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='MultaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(help_text='Número de cuota atrasada')),
                ('tipo', models.CharField(choices=[('primera', 'Primera vez $10'), ('reincidente', 'Reincidente $30')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='creditos.credito')),
            ],
        ),
        migrations.CreateModel(
            name='PagoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pago', models.IntegerField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('comprobante_referencia', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('reportado', 'Reportado'), ('verificado', 'Verificado'), ('rechazado', 'Rechazado')], default='reportado', max_length=20)),
                ('es_abono', models.BooleanField(default=False, help_text='Para no mensualizado')),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='creditos.credito')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero_pago'],
            },
        ),
    ]
