# Generated by Django 6.0.3 on 2026-04-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocredito',
            name='comprobante_archivo',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/pagos_credito/'),
        ),
    ]
