# Generated by Django 6.0.3 on 2026-04-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_pagocredito_comprobante_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='comprobante_desembolso',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/desembolsos_credito/'),
        ),
    ]
