# Generated by Django 6.0.3 on 2026-04-29 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_credito_comprobante_desembolso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=True)),
                ('forzada', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=300)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_admin', to='creditos.credito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_credito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aprobacion administrativa de credito',
                'verbose_name_plural': 'Aprobaciones administrativas de creditos',
                'ordering': ['fecha'],
                'unique_together': {('credito', 'usuario')},
            },
        ),
    ]
