# Generated by Django 6.0.3 on 2026-05-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_aprobacioncredito'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagocredito',
            unique_together={('credito', 'numero_pago')},
        ),
    ]
